name: 'omero-basic'
channels:
  - conda-forge
  - ome
dependencies:
  - python=3.6
  - pip
  - omero-py
  - zeroc-ice36-python
  - pip:
    - numpy
#    - ome-zarr
#    - dask-image
#    - stardist
#    - tensorflow